### PR TITLE
Rewrite DAS.js for V3 bike

### PR DESCRIPTION
**Pull request by emilytrau**
## Description

Rewrite DAS.js to use the V3 protocol/sensors. Teensy communication has been removed leaving just the ANT+ sensor.

## Screenshots

N/A

## Steps to Test

`node DAS.js`

### CODE REVIEW

**Comment by hallgchris** [comment]
Confirmed working with heart rate sensor.
image

**Review by hallgchris — APPROVED** [review]
Looks great to me!

**Review by khanguslee — APPROVED** [review]
LGTM. Love your work mate. Keep it up.

**Comment by khanguslee** [comment]
@angustrau ready to merge in if you're happy with it

**Pull request merged**
