### PR TITLE
Update mqtt_test.py to replay a previously recorded csv file over MQTT

### PR DESCRIPTION
**Pull request by hallgchris**

### CODE REVIEW

**Comment by hallgchris** [comment]
[MQTT DAS test script to output actual race data](https://trello.com/c/KfoBGEFh/36-mqtt-das-test-script-to-output-actual-race-data)

**Comment by hallgchris** [comment]
[MQTT DAS test script to output actual race data](https://trello.com/c/KfoBGEFh/36-mqtt-das-test-script-to-output-actual-race-data)

**Review by harsilspatel — APPROVED** [review]
looks good to me!

**Comment by harsilspatel** [comment]
do we also want to write some test cases to ensure that the newly added features work or would that be an overkill? 🤔

**Comment by khanguslee** [comment]
> do we also want to write some test cases to ensure that the newly added features work or would that be an overkill? 🤔

Not sure how you would test arduino code. 

Also doesn't make sense to make a test for your test? But we certainly do need tests in the other files!

**Review by khanguslee — APPROVED** [review]
This is exactly what I always wanted. Good job @hallgchris ! 

Only thing I have to say is to make sure you branch off for different features you are working on. Good catch on passing args into the functions!

**Pull request merged**
