### PR TITLE
harsilspatel/linting

### PR DESCRIPTION
**Pull request by harsilspatel**

### CODE REVIEW

**Comment by khanguslee** [comment]
Is this ready to be checked? @harsilspatel

**Comment by harsilspatel** [comment]
wait i don't even remember what had happened here lol, i'll get back on this one

**Review by hallgchris — COMMENTED** [review]
It's looking good, just two things:
- Do we intend to switch from Travis to Github Actions? If so, we probably don't need the .travis.yml
- Somehow a .DS_Store sneaked into the root directory

**Comment by khanguslee** [comment]
Let's continue with Travis for now. Do github actions in another task. Soz @angustrau

**Review by emilytrau — DISMISSED** [review]

**Review by khanguslee — APPROVED** [review]

**Pull request merged**
