### PR TITLE
Replace gps_location field with gps_lat, gps_long and gps_alt

### PR DESCRIPTION
**Pull request by hallgchris**
Depends on Monash-Human-Power/MHP-DAS-Web-Server#15

### CODE REVIEW

**Review by harsilspatel — APPROVED** [review]

**Comment by harsilspatel** [comment]
good work @hallgchris 
i think we should also setup pylint at some point :)

**Comment by hallgchris** [comment]
> i think we should also setup pylint at some point :)

I actually use pylint in my editor and that would give the excuse to get rid of all the editor warnings in everyone's code :joy: I vote yes

**Comment by khanguslee** [comment]
> good work @hallgchris
> i think we should also setup pylint at some point :)

Sounds good to me. Can someone make a PR hehehe

**Review by khanguslee — APPROVED** [review]
I'm gonna approve this. However, I will need to check this manually with the real DAS before we can confirm that it works.

**Comment by hallgchris** [comment]
[Log longitude, latitude and altitude in separate columns](https://trello.com/c/1f5gCuWt/2-log-longitude-latitude-and-altitude-in-separate-columns)

**Pull request merged**
